/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmsproj;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author vedant
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminID = new javax.swing.JLabel();
        AdminIDfield = new javax.swing.JTextField();
        AdminPWfield = new javax.swing.JPasswordField();
        AdminPW = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminID.setText("Admin ID");

        AdminIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIDfieldActionPerformed(evt);
            }
        });

        AdminPW.setText("Password");

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setText("Admin Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminPW, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdminIDfield)
                                    .addComponent(AdminPWfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminID)
                    .addComponent(AdminIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminPW)
                    .addComponent(AdminPWfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIDfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminIDfieldActionPerformed
    AdminPage ap = new AdminPage();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
         // String sql = "select * from login_credentials where username = ? and password = ?";

        Encryption enc=new Encryption("PdSgVkYp3s6v9y$B");
        ResultSet rs=null;
        PreparedStatement ps=null;
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
                //String sql="select pass from adminlogin_credentials where username=?";
                ps = conn.prepareStatement("select pass from adminlogin_credentials where username=?");
                
                ps.setString(1, AdminIDfield.getText());
                char[] pass1=AdminPWfield.getPassword();
                String pass=String.valueOf(pass1);
                String encpass=enc.encrypt(pass);
               // String dbpass=ReceptionistPWfield.getText();
                
                System.out.println(encpass);
                      
                      
                String username="";
              //  ps.setString(2, "");
                //ps.setString(2, new String(ReceptionistPWfield.getPassword()));
                
                rs = ps.executeQuery();
                rs.next();
                    
                //   username =ReceptionistIDfield.getText();*/
              String dbpass=rs.getString("pass");
              
              /*  ps=conn.prepareStatement(sql);
                ps.setString(1,dbpass);
                rs=ps.executeQuery();
                */System.out.println(dbpass);
                System.out.println(encpass.equals(dbpass));
                if (encpass.equals(dbpass))
                {
                    ap.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Welcome  " + AdminIDfield.getText(), "Successful", JOptionPane.PLAIN_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(null, "Inavlid" , "Unuccessful", JOptionPane.ERROR_MESSAGE);
            }
        
        
        
        /*
        String sql="select password from login_credentials where username=?";
        Encryption enc=new Encryption("PdSgVkYp3s6v9y$B");  
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","1234")) {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, AdminIDfield.getText());
                char[] pass1=AdminPWfield.getPassword();
                String pass=String.valueOf(pass1);
                String encpass=enc.encrypt(pass);
                
                
                System.out.println(encpass);
              //  ps.setString(2, "");
                //ps.setString(2, new String(ReceptionistPWfield.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                if (!encpass.equals(pass))
                {
                    ap.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Welcome  " + AdminIDfield.getText(), "Successful", JOptionPane.PLAIN_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(null, "Inavlid" , "Unuccessful", JOptionPane.ERROR_MESSAGE);
            }
        }
       /* try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, AdminIDfield.getText());
                ps.setString(2, new String(AdminPWfield.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                if (rs.next())
                {
                    ap.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Welcome  " + AdminIDfield.getText(), "Successful", JOptionPane.PLAIN_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(null, "Invalid" , "Unsuccessful", JOptionPane.ERROR_MESSAGE);
                
                conn.close();
        }*/
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminID;
    private javax.swing.JTextField AdminIDfield;
    private javax.swing.JLabel AdminPW;
    private javax.swing.JPasswordField AdminPWfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
