/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dbmsproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author vedan
 */
public class AlterOrder extends javax.swing.JFrame {

    /** Creates new form AlterOrder */
    public AlterOrder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Oquantityfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        Hidfield = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        Odatefield = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        Oblood_groupfield = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        Oidfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Order Type:");

        jLabel5.setText("If Specific, Order Type:");

        jLabel6.setText("Blood Group:");

        jLabel7.setText("Order ID:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Whole Blood");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Specific");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Plasma");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("RBC");

        jLabel1.setText("Hospital ID:");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Platelets");

        jLabel2.setText("Quantity:");

        jLabel3.setText("Date: (YYYY-MM-DD)");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update as per ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete as per ID");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel8.setText("Admin - Alter Order Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Oidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oblood_groupfield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Odatefield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Oquantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Oidfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Hidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Odatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Oblood_groupfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Oquantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
            //insert into order_details values (?,?,?); insert into specific_order values (?,?,?);
            String sql1 = "insert into orders values (?,?,?);";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ps1.setString(1, Hidfield.getText());
            ps1.setString(2, Oidfield.getText());
            ps1.setString(3, Odatefield.getText());
            
            String sql2 = "insert into order_details values (?,?,?,?);";
            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setString(1, Oidfield.getText());
            ps2.setString(2, Oquantityfield.getText());
            String otype="none"; String sotype="none";
            if(jRadioButton1.isSelected())
                otype = jRadioButton1.getText();
            if(jRadioButton2.isSelected())
            {
                otype = jRadioButton2.getText();
                
                if(jRadioButton3.isSelected())
                    sotype = jRadioButton3.getText();
                if(jRadioButton4.isSelected())
                    sotype = jRadioButton4.getText();
                if(jRadioButton5.isSelected())
                    sotype = jRadioButton5.getText();
            }
            ps2.setString(3, otype);
            ps2.setString(4, Oblood_groupfield.getText());
            
            String sql3 = "insert into specific_order values (?,?,?);";
            PreparedStatement ps3= conn.prepareStatement(sql3);
            ps3.setString(1, Oidfield.getText());
            ps3.setString(2, sotype);
            ps3.setString(3, Oblood_groupfield.getText());
            
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps3.executeUpdate();
            Oidfield.setText("");
            Hidfield.setText("");
            Oblood_groupfield.setText("");
            Odatefield.setText("");
            Oquantityfield.setText("");
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            JOptionPane.showMessageDialog(null, "Order Placed Successfully for  " + Oidfield.getText(), "Successful", JOptionPane.PLAIN_MESSAGE);
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
            int flag = 0;
            String sql1 = "select * from orders where order_id=?";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ps1.setInt(1, Integer.parseInt(Oidfield.getText()));
            ResultSet rs1 = ps1.executeQuery();
            
            
            if (rs1.next())
            {   
                flag = 1;
                Hidfield.setText(rs1.getString("hospital_id"));
                Odatefield.setText(rs1.getString("order_date"));
            }
            if (flag == 1)
            {   
                String sql2 = "select * from order_details where order_id=?";
                PreparedStatement ps2 = conn.prepareStatement(sql2);
                ps2.setInt(1, Integer.parseInt(Oidfield.getText()));
                ResultSet rs2 = ps2.executeQuery();
                Oquantityfield.setText(rs2.getString("quantity"));
                if(rs2.next())
                {
                    if(rs2.getString("order_type").equals("Whole Blood"))
                        jRadioButton1.setSelected(true);
                    if(rs2.getString("order_type").equals("Specific"))
                        jRadioButton2.setSelected(true);
                    Oblood_groupfield.setText(rs2.getString("blood_grp"));
                }
                
                String sql3 = "select * from specific_order where order_id=?";
                PreparedStatement ps3 = conn.prepareStatement(sql3);
                ps3.setInt(1, Integer.parseInt(Oidfield.getText()));
                ResultSet rs3 = ps3.executeQuery();
                if(rs3.next())
                {
                    if(rs3.getString("order_component").equals("Plasma"))
                        jRadioButton3.setSelected(true);
                    if(rs3.getString("order_component").equals("RBC"))
                        jRadioButton4.setSelected(true);
                    if(rs3.getString("order_component").equals("Platelets"))
                        jRadioButton5.setSelected(true);
                }
            }
            else
            JOptionPane.showMessageDialog(null, "No Record Found" , "Unuccessful", JOptionPane.ERROR_MESSAGE);

            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
            String sql1 = "update orders set order_date=? where order_id=?";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            
            ps1.setString(1, Odatefield.getText());
            ps1.setString(2, Oidfield.getText());
            
            String sql2 = "update order_details set quantity=?, order_type=?, blood_grp=? where order_id=?";
            PreparedStatement ps2 = conn.prepareStatement(sql2);
        
            String otype="none"; String sotype="none";
            if(jRadioButton1.isSelected())
                otype = jRadioButton1.getText();
            if(jRadioButton2.isSelected())
            {
                otype = jRadioButton2.getText();
                
                if(jRadioButton3.isSelected())
                    sotype = jRadioButton3.getText();
                if(jRadioButton4.isSelected())
                    sotype = jRadioButton4.getText();
                if(jRadioButton5.isSelected())
                    sotype = jRadioButton5.getText();
            }
            ps2.setString(1, Oquantityfield.getText());
            ps2.setString(2, otype);
            ps2.setString(3, Oblood_groupfield.getText());
            ps2.setString(4, Oidfield.getText());
            
            String sql3 = "update specific_order set order_component=?, blood_group=? where order_id=?";
            PreparedStatement ps3= conn.prepareStatement(sql3);
            ps3.setString(1, sotype);
            ps3.setString(2, Oblood_groupfield.getText());
            ps3.setString(3, Oidfield.getText());
            
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps3.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successful for  " + Oidfield.getText(), "Successful", JOptionPane.PLAIN_MESSAGE);
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","asdf1234");
            
            String sql1 = "delete from orders where order_id=?";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ps1.setInt(1, Integer.parseInt(Oidfield.getText()));
            ps1.executeUpdate();
            
            String sql2 = "delete from order_details where order_id=?";
            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setInt(1, Integer.parseInt(Oidfield.getText()));
            ps2.executeUpdate();
            
            String sql3 = "delete from specific_order where order_id=?";
            PreparedStatement ps3 = conn.prepareStatement(sql3);
            ps3.setInt(1, Integer.parseInt(Oidfield.getText()));
            ps3.executeUpdate();
            
            Oidfield.setText("");
            Hidfield.setText("");
            Oblood_groupfield.setText("");
            Odatefield.setText("");
            Oquantityfield.setText("");
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hidfield;
    private javax.swing.JTextField Oblood_groupfield;
    private javax.swing.JTextField Odatefield;
    private javax.swing.JTextField Oidfield;
    private javax.swing.JTextField Oquantityfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables

}
